// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblEOE8HIpYExSNsxqyV7ilNNiyBjRw8U',
    appId: '1:172520128766:web:668255c49579eb8657e5af',
    messagingSenderId: '172520128766',
    projectId: 'jana-b97b7',
    authDomain: 'jana-b97b7.firebaseapp.com',
    storageBucket: 'jana-b97b7.appspot.com',
    measurementId: 'G-CWPWKPDMKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Tf_WG_qCWeYD4-n5xOUhiqpXZI4871s',
    appId: '1:172520128766:android:2e77c67595375bf657e5af',
    messagingSenderId: '172520128766',
    projectId: 'jana-b97b7',
    storageBucket: 'jana-b97b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2eb2w0JsLKDh2dcpPo-vE8jIpsJQw8ls',
    appId: '1:172520128766:ios:bbe9e619ea1ed08b57e5af',
    messagingSenderId: '172520128766',
    projectId: 'jana-b97b7',
    storageBucket: 'jana-b97b7.appspot.com',
    iosBundleId: 'com.example.janaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2eb2w0JsLKDh2dcpPo-vE8jIpsJQw8ls',
    appId: '1:172520128766:ios:7f0f00e1050c01ed57e5af',
    messagingSenderId: '172520128766',
    projectId: 'jana-b97b7',
    storageBucket: 'jana-b97b7.appspot.com',
    iosBundleId: 'com.example.janaProject.RunnerTests',
  );
}
